// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebDbApp.Data;

#nullable disable

namespace MyWebDbApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "eb227aa5-658f-4d1b-bcea-d5338d68f9c9",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "49b478bd-9ee6-42f1-8cbb-0923cba9ac42",
                            Name = "Office",
                            NormalizedName = "OFFICE"
                        },
                        new
                        {
                            Id = "239074ba-0164-4b80-8526-17e1d56b892f",
                            Name = "Worker",
                            NormalizedName = "WORKER"
                        },
                        new
                        {
                            Id = "80f41492-3d55-4744-8f7b-61d5c940a9db",
                            Name = "Chief",
                            NormalizedName = "CHIEF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "77fc46c1-383d-44ee-8a31-c85acf20c811",
                            RoleId = "eb227aa5-658f-4d1b-bcea-d5338d68f9c9"
                        },
                        new
                        {
                            UserId = "d28e32a2-e920-4667-829e-c3af3b5c2669",
                            RoleId = "49b478bd-9ee6-42f1-8cbb-0923cba9ac42"
                        },
                        new
                        {
                            UserId = "af086b82-923f-450d-b20b-7bb21b164f34",
                            RoleId = "49b478bd-9ee6-42f1-8cbb-0923cba9ac42"
                        },
                        new
                        {
                            UserId = "d6f5a6eb-c19a-472e-88e6-7c68d2d6eb72",
                            RoleId = "239074ba-0164-4b80-8526-17e1d56b892f"
                        },
                        new
                        {
                            UserId = "29f445e3-c72e-4cd1-950d-961c495095a3",
                            RoleId = "80f41492-3d55-4744-8f7b-61d5c940a9db"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyWebDbApp.Areas.Identity.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "77fc46c1-383d-44ee-8a31-c85acf20c811",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f55fd4e-49ef-4f23-baed-2a77e937c426",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOdp0X5ua0wJxECYQqtOD/m75tcItsNW4YuHnKiewhZvdVfibnRouVIFpl63BkavWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb20e840-c639-415f-a389-57824416c590",
                            TwoFactorEnabled = false,
                            UserName = "admin@abc.com"
                        },
                        new
                        {
                            Id = "d28e32a2-e920-4667-829e-c3af3b5c2669",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfebbde6-96e1-44b1-99e6-c33d9bc07b5a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "OFFICE1@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF8eus+P25LMHy+9UW3YIujHQViBHs0M/sBPt+VJdQJ6bmXWBmz8zgU6AP0AiLLFWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fb64a2c-3bf8-4d5f-a010-8746d4df16b7",
                            TwoFactorEnabled = false,
                            UserName = "office1@abc.com"
                        },
                        new
                        {
                            Id = "af086b82-923f-450d-b20b-7bb21b164f34",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "23bf58b9-9150-4b43-acd7-d1e0076b3e09",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "OFFICE2@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPJo/Wsd6ww2c4OCl0gf8h4lyKlgHleEQT6yn6RoktYDIMyohuFKvpu5JDICODTAWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68561ea9-96b6-4e57-813d-b9066d7f2acd",
                            TwoFactorEnabled = false,
                            UserName = "office2@abc.com"
                        },
                        new
                        {
                            Id = "d6f5a6eb-c19a-472e-88e6-7c68d2d6eb72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c3ba316-6e42-47bc-bf1b-748a55b5e029",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "WORKER@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN9byP4OeOOCfFJG8vigKUquCYynqQWLKBvxeQSWC4wpx6J8gWBBH3Sl8oZU9js/yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74767078-3196-4593-a891-8c112ef17d92",
                            TwoFactorEnabled = false,
                            UserName = "worker@abc.com"
                        },
                        new
                        {
                            Id = "29f445e3-c72e-4cd1-950d-961c495095a3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f7d29a1-7b1f-45f2-b379-8698bbd72022",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "CHIEF@ABC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDEQdpwpUK+zwo7EIZfWCB9ZXtGdO1fVenBukkttMT6EVrWBgGZx8wkhxZUXnV/nAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d87362f-6c95-41d9-a539-05e9e47ccb6e",
                            TwoFactorEnabled = false,
                            UserName = "chief@abc.com"
                        });
                });

            modelBuilder.Entity("MyWebDbApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiefId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChiefId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desk",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "Chair",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desk",
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 32,
                            Name = "Chair",
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desk",
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chair",
                            WorkspaceId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Desk",
                            WorkspaceId = 4
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chair",
                            WorkspaceId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Desk",
                            WorkspaceId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chair",
                            WorkspaceId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Desk",
                            WorkspaceId = 6
                        },
                        new
                        {
                            Id = 36,
                            Name = "Chair",
                            WorkspaceId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Desk",
                            WorkspaceId = 7
                        },
                        new
                        {
                            Id = 37,
                            Name = "Chair",
                            WorkspaceId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Desk",
                            WorkspaceId = 8
                        },
                        new
                        {
                            Id = 38,
                            Name = "Chair",
                            WorkspaceId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Desk",
                            WorkspaceId = 9
                        },
                        new
                        {
                            Id = 39,
                            Name = "Chair",
                            WorkspaceId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Desk",
                            WorkspaceId = 10
                        },
                        new
                        {
                            Id = 40,
                            Name = "Chair",
                            WorkspaceId = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Desk",
                            WorkspaceId = 11
                        },
                        new
                        {
                            Id = 41,
                            Name = "Chair",
                            WorkspaceId = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "Desk",
                            WorkspaceId = 12
                        },
                        new
                        {
                            Id = 42,
                            Name = "Chair",
                            WorkspaceId = 12
                        },
                        new
                        {
                            Id = 13,
                            Name = "Desk",
                            WorkspaceId = 13
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chair",
                            WorkspaceId = 13
                        },
                        new
                        {
                            Id = 14,
                            Name = "Desk",
                            WorkspaceId = 14
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chair",
                            WorkspaceId = 14
                        },
                        new
                        {
                            Id = 15,
                            Name = "Desk",
                            WorkspaceId = 15
                        },
                        new
                        {
                            Id = 45,
                            Name = "Chair",
                            WorkspaceId = 15
                        },
                        new
                        {
                            Id = 16,
                            Name = "Desk",
                            WorkspaceId = 16
                        },
                        new
                        {
                            Id = 46,
                            Name = "Chair",
                            WorkspaceId = 16
                        },
                        new
                        {
                            Id = 17,
                            Name = "Desk",
                            WorkspaceId = 17
                        },
                        new
                        {
                            Id = 47,
                            Name = "Chair",
                            WorkspaceId = 17
                        },
                        new
                        {
                            Id = 18,
                            Name = "Desk",
                            WorkspaceId = 18
                        },
                        new
                        {
                            Id = 48,
                            Name = "Chair",
                            WorkspaceId = 18
                        },
                        new
                        {
                            Id = 19,
                            Name = "Desk",
                            WorkspaceId = 19
                        },
                        new
                        {
                            Id = 49,
                            Name = "Chair",
                            WorkspaceId = 19
                        },
                        new
                        {
                            Id = 20,
                            Name = "Desk",
                            WorkspaceId = 20
                        },
                        new
                        {
                            Id = 50,
                            Name = "Chair",
                            WorkspaceId = 20
                        },
                        new
                        {
                            Id = 21,
                            Name = "Desk",
                            WorkspaceId = 21
                        },
                        new
                        {
                            Id = 51,
                            Name = "Chair",
                            WorkspaceId = 21
                        },
                        new
                        {
                            Id = 22,
                            Name = "Desk",
                            WorkspaceId = 22
                        },
                        new
                        {
                            Id = 52,
                            Name = "Chair",
                            WorkspaceId = 22
                        },
                        new
                        {
                            Id = 23,
                            Name = "Desk",
                            WorkspaceId = 23
                        },
                        new
                        {
                            Id = 53,
                            Name = "Chair",
                            WorkspaceId = 23
                        },
                        new
                        {
                            Id = 24,
                            Name = "Desk",
                            WorkspaceId = 24
                        },
                        new
                        {
                            Id = 54,
                            Name = "Chair",
                            WorkspaceId = 24
                        },
                        new
                        {
                            Id = 25,
                            Name = "Desk",
                            WorkspaceId = 25
                        },
                        new
                        {
                            Id = 55,
                            Name = "Chair",
                            WorkspaceId = 25
                        },
                        new
                        {
                            Id = 26,
                            Name = "Desk",
                            WorkspaceId = 26
                        },
                        new
                        {
                            Id = 56,
                            Name = "Chair",
                            WorkspaceId = 26
                        },
                        new
                        {
                            Id = 27,
                            Name = "Desk",
                            WorkspaceId = 27
                        },
                        new
                        {
                            Id = 57,
                            Name = "Chair",
                            WorkspaceId = 27
                        },
                        new
                        {
                            Id = 28,
                            Name = "Desk",
                            WorkspaceId = 28
                        },
                        new
                        {
                            Id = 58,
                            Name = "Chair",
                            WorkspaceId = 28
                        },
                        new
                        {
                            Id = 29,
                            Name = "Desk",
                            WorkspaceId = 29
                        },
                        new
                        {
                            Id = 59,
                            Name = "Chair",
                            WorkspaceId = 29
                        },
                        new
                        {
                            Id = 30,
                            Name = "Desk",
                            WorkspaceId = 30
                        },
                        new
                        {
                            Id = 60,
                            Name = "Chair",
                            WorkspaceId = 30
                        });
                });

            modelBuilder.Entity("MyWebDbApp.Models.Occupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Occupancies");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Room 1",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Room 2",
                            Type = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Room 3",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Room 4",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Room 5",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Room 6",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Room 7",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Room 8",
                            Type = 5
                        },
                        new
                        {
                            Id = 9,
                            Name = "Room 9",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Room 10",
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Homeoffice",
                            Type = 6
                        });
                });

            modelBuilder.Entity("MyWebDbApp.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Workspace 1",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Workspace 2",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Workspace 3",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "Workspace 4",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 5,
                            Name = "Workspace 5",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 6,
                            Name = "Workspace 6",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 7,
                            Name = "Workspace 7",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 8,
                            Name = "Workspace 8",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 9,
                            Name = "Workspace 9",
                            RoomId = 10
                        },
                        new
                        {
                            Id = 10,
                            Name = "Workspace 10",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Workspace 11",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Workspace 12",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Workspace 13",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 14,
                            Name = "Workspace 14",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Workspace 15",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "Workspace 16",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 17,
                            Name = "Workspace 17",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 18,
                            Name = "Workspace 18",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 19,
                            Name = "Workspace 19",
                            RoomId = 10
                        },
                        new
                        {
                            Id = 20,
                            Name = "Workspace 20",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Workspace 21",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Workspace 22",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Workspace 23",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "Workspace 24",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 25,
                            Name = "Workspace 25",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "Workspace 26",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 27,
                            Name = "Workspace 27",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 28,
                            Name = "Workspace 28",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 29,
                            Name = "Workspace 29",
                            RoomId = 10
                        },
                        new
                        {
                            Id = 30,
                            Name = "Workspace 30",
                            RoomId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyWebDbApp.Areas.Identity.Data.AppUser", b =>
                {
                    b.HasOne("MyWebDbApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Department", b =>
                {
                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", "Chief")
                        .WithMany()
                        .HasForeignKey("ChiefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chief");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Equipment", b =>
                {
                    b.HasOne("MyWebDbApp.Models.Workspace", "Workspace")
                        .WithMany("Equipment")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Occupancy", b =>
                {
                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("MyWebDbApp.Models.Room", "Room")
                        .WithMany("Occupancies")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyWebDbApp.Areas.Identity.Data.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("MyWebDbApp.Models.Workspace", null)
                        .WithMany("Occupancies")
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("Employee");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Workspace", b =>
                {
                    b.HasOne("MyWebDbApp.Models.Room", "Room")
                        .WithMany("Workspaces")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Room", b =>
                {
                    b.Navigation("Occupancies");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("MyWebDbApp.Models.Workspace", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
